newPRWelcomeComment: |
  Thanks for opening a pull request and helping make Lic better! Someone from the Lic team will take a look at your pull request shortly and leave any feedback. Please make sure that your pull request has tests for any changes or added functionality.

  We use Travis CI to test and make sure your change works functionally and uses acceptable conventions, you can review the current progress of Travis CI in the PR status window below.

  If you have any questions or concerns that you wish to ask, feel free to leave a comment in this PR or join our #lic channel on [Slack](http://slack.lic.io/).

  For more information about contributing to the Lic project feel free to review our [CONTRIBUTING](https://github.com/lic/lic/blob/master/doc/contributing/README.md) guide

