---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - ruby
  fixme:
    enabled: true
  rubocop:
    enabled: false
ratings:
  paths:
  - "**.rb"
  - "bin/*"
  - "exe/*"
exclude_paths:
- lic.gemspec
- "*.md"
- lib/lic/ssl_certs/*.pem
- lib/lic/vendor/**/*
- lib/lic/templates/**/*.tt
- man/*
- spec/**/*
- Rakefile
