#!/usr/bin/env ruby
# frozen_string_literal: true

# Exit cleanly from an early interrupt
Signal.trap("INT") do
  Lic.ui.debug("\n#{caller.join("\n")}") if defined?(Lic)
  exit 1
end

$:.unshift(File.expand_path("../../lib", __FILE__))
require "lic"
# Check if an older version of lic is installed
$LOAD_PATH.each do |path|
  next unless path =~ %r{/lic-0\.(\d+)} && $1.to_i < 9
  err = String.new
  err << "Looks like you have a version of lic that's older than 0.9.\n"
  err << "Please remove your old versions.\n"
  err << "An easy way to do this is by running `gem cleanup lic`."
  abort(err)
end

require "lic/friendly_errors"
Lic.with_friendly_errors do
  require "lic/cli"

  # Allow any command to use --help flag to show help for that command
  help_flags = %w[--help -h]
  help_flag_used = ARGV.any? {|a| help_flags.include? a }
  args = help_flag_used ? Lic::CLI.reformatted_help_args(ARGV) : ARGV

  Lic::CLI.start(args, :debug => true)
end
