# frozen_string_literal: true

RSpec.describe "lic binstubs <gem>" do
  context "when the gem exists in the lockfile" do
    it "sets up the binstub" do
      install_gemfile <<-G
        source "file://#{gem_repo1}"
        gem "rack"
      G

      lic "binstubs rack"

      expect(licd_app("bin/rackup")).to exist
    end

    it "does not install other binstubs" do
      install_gemfile <<-G
        source "file://#{gem_repo1}"
        gem "rack"
        gem "rails"
      G

      lic "binstubs rails"

      expect(licd_app("bin/rackup")).not_to exist
      expect(licd_app("bin/rails")).to exist
    end

    it "does install multiple binstubs" do
      install_gemfile <<-G
        source "file://#{gem_repo1}"
        gem "rack"
        gem "rails"
      G

      lic "binstubs rails rack"

      expect(licd_app("bin/rackup")).to exist
      expect(licd_app("bin/rails")).to exist
    end

    it "allows installing all binstubs" do
      install_gemfile! <<-G
        source "file://#{gem_repo1}"
        gem "rails"
      G

      lic! :binstubs, :all => true

      expect(licd_app("bin/rails")).to exist
      expect(licd_app("bin/rake")).to exist
    end

    it "displays an error when used without any gem" do
      install_gemfile <<-G
        source "file://#{gem_repo1}"
        gem "rack"
      G

      lic "binstubs"
      expect(exitstatus).to eq(1) if exitstatus
      expect(out).to include("`lic binstubs` needs at least one gem to run.")
    end

    it "displays an error when used with --all and gems" do
      install_gemfile <<-G
        source "file://#{gem_repo1}"
        gem "rack"
      G

      lic "binstubs rack", :all => true
      expect(last_command).to be_failure
      expect(last_command.lic_err).to include("Cannot specify --all with specific gems")
    end

    context "when generating lic binstub outside lic" do
      it "should abort" do
        install_gemfile <<-G
          source "file://#{gem_repo1}"
          gem "rack"
        G

        lic "binstubs rack"

        File.open("bin/lic", "wb") do |file|
          file.print "OMG"
        end

        sys_exec "bin/rackup"

        expect(last_command.stderr).to include("was not generated by Lic")
      end
    end

    context "the lic binstub" do
      before do
        if system_lic_version == :lic
          system_gems :lic
        elsif system_lic_version
          build_repo4 do
            build_gem "lic", system_lic_version do |s|
              s.executables = "lic"
              s.bindir = "exe"
              s.write "exe/lic", "puts %(system lic #{system_lic_version}\\n\#{ARGV.inspect})"
            end
          end
          system_gems "lic-#{system_lic_version}", :gem_repo => gem_repo4
        end
        build_repo2 do
          build_gem "prints_loaded_gems", "1.0" do |s|
            s.executables = "print_loaded_gems"
            s.bindir = "exe"
            s.write "exe/print_loaded_gems", <<-R
              specs = Gem.loaded_specs.values.reject {|s| Lic.rubygems.spec_default_gem?(s) }
              puts specs.map(&:full_name).sort.inspect
            R
          end
        end
        install_gemfile! <<-G
          source "file://#{gem_repo2}"
          gem "rack"
          gem "prints_loaded_gems"
        G
        lic! "binstubs lic rack prints_loaded_gems"
      end

      let(:system_lic_version) { Lic::VERSION }

      it "runs lic" do
        sys_exec! "#{licd_app("bin/lic")} install"
        expect(out).to eq %(system lic #{system_lic_version}\n["install"])
      end

      context "when LIC_VERSION is set" do
        it "runs the correct version of lic" do
          sys_exec "LIC_VERSION='999.999.999' #{licd_app("bin/lic")} install"
          expect(exitstatus).to eq(42) if exitstatus
          expect(last_command.stderr).to include("Activating lic (999.999.999) failed:").
            and include("To install the version of lic this project requires, run `gem install lic -v '999.999.999'`")
        end
      end

      context "when a lockfile exists with a locked lic version" do
        it "runs the correct version of lic when the version is newer" do
          lockfile lockfile.gsub(system_lic_version, "999.999.999")
          sys_exec "#{licd_app("bin/lic")} install"
          expect(exitstatus).to eq(42) if exitstatus
          expect(last_command.stderr).to include("Activating lic (999.999.999) failed:").
            and include("To install the version of lic this project requires, run `gem install lic -v '999.999.999'`")
        end

        it "runs the correct version of lic when the version is older" do
          simulate_lic_version "55"
          lockfile lockfile.gsub(system_lic_version, "44.0")
          sys_exec "#{licd_app("bin/lic")} install"
          expect(exitstatus).to eq(42) if exitstatus
          expect(last_command.stderr).to include("Activating lic (44.0) failed:").
            and include("To install the version of lic this project requires, run `gem install lic -v '44.0'`")
        end

        it "runs the correct version of lic when the version is a pre-release" do
          simulate_lic_version "55"
          lockfile lockfile.gsub(system_lic_version, "2.12.0.a")
          sys_exec "#{licd_app("bin/lic")} install"
          expect(exitstatus).to eq(42) if exitstatus
          expect(last_command.stderr).to include("Activating lic (2.12.0.a) failed:").
            and include("To install the version of lic this project requires, run `gem install lic -v '2.12.0.a'`")
        end
      end

      context "when update --lic is called" do
        before { lockfile.gsub(system_lic_version, "1.1.1") }

        it "calls through to the latest lic version" do
          sys_exec! "#{licd_app("bin/lic")} update --lic"
          expect(last_command.stdout).to eq %(system lic #{system_lic_version}\n["update", "--lic"])
        end

        it "calls through to the explicit lic version" do
          sys_exec "#{licd_app("bin/lic")} update --lic=999.999.999"
          expect(exitstatus).to eq(42) if exitstatus
          expect(last_command.stderr).to include("Activating lic (999.999.999) failed:").
            and include("To install the version of lic this project requires, run `gem install lic -v '999.999.999'`")
        end
      end

      context "without a lockfile" do
        it "falls back to the latest installed lic" do
          FileUtils.rm licd_app("Gemfile.lock")
          sys_exec! licd_app("bin/lic").to_s
          expect(out).to eq "system lic #{system_lic_version}\n[]"
        end
      end

      context "using another binstub" do
        let(:system_lic_version) { :lic }
        it "loads all gems" do
          sys_exec! licd_app("bin/print_loaded_gems").to_s
          expect(out).to eq %(["lic-#{Lic::VERSION}", "prints_loaded_gems-1.0", "rack-1.2"])
        end

        context "when requesting a different lic version" do
          before { lockfile lockfile.gsub(Lic::VERSION, "999.999.999") }

          it "attempts to load that version", :ruby_repo do
            sys_exec licd_app("bin/rackup").to_s
            expect(exitstatus).to eq(42) if exitstatus
            expect(last_command.stderr).to include("Activating lic (999.999.999) failed:").
              and include("To install the version of lic this project requires, run `gem install lic -v '999.999.999'`")
          end
        end
      end
    end

    it "installs binstubs from git gems" do
      FileUtils.mkdir_p(lib_path("foo/bin"))
      FileUtils.touch(lib_path("foo/bin/foo"))
      build_git "foo", "1.0", :path => lib_path("foo") do |s|
        s.executables = %w[foo]
      end
      install_gemfile <<-G
        gem "foo", :git => "#{lib_path("foo")}"
      G

      lic "binstubs foo"

      expect(licd_app("bin/foo")).to exist
    end

    it "installs binstubs from path gems" do
      FileUtils.mkdir_p(lib_path("foo/bin"))
      FileUtils.touch(lib_path("foo/bin/foo"))
      build_lib "foo", "1.0", :path => lib_path("foo") do |s|
        s.executables = %w[foo]
      end
      install_gemfile <<-G
        gem "foo", :path => "#{lib_path("foo")}"
      G

      lic "binstubs foo"

      expect(licd_app("bin/foo")).to exist
    end

    it "sets correct permissions for binstubs" do
      with_umask(0o002) do
        install_gemfile <<-G
          source "file://#{gem_repo1}"
          gem "rack"
        G

        lic "binstubs rack"
        binary = licd_app("bin/rackup")
        expect(File.stat(binary).mode.to_s(8)).to eq("100775")
      end
    end

    context "when using --shebang" do
      it "sets the specified shebang for the the binstub" do
        install_gemfile <<-G
          source "file://#{gem_repo1}"
          gem "rack"
        G

        lic "binstubs rack --shebang jruby"

        expect(File.open("bin/rackup").gets).to eq("#!/usr/bin/env jruby\n")
      end
    end
  end

  context "when the gem doesn't exist" do
    it "displays an error with correct status" do
      install_gemfile <<-G
        source "file://#{gem_repo1}"
      G

      lic "binstubs doesnt_exist"

      expect(exitstatus).to eq(7) if exitstatus
      expect(out).to include("Could not find gem 'doesnt_exist'.")
    end
  end

  context "--path" do
    it "sets the binstubs dir" do
      install_gemfile <<-G
        source "file://#{gem_repo1}"
        gem "rack"
      G

      lic "binstubs rack --path exec"

      expect(licd_app("exec/rackup")).to exist
    end

    it "setting is saved for lic install", :lic => "< 2" do
      install_gemfile <<-G
        source "file://#{gem_repo1}"
        gem "rack"
        gem "rails"
      G

      lic! "binstubs rack", forgotten_command_line_options([:path, :bin] => "exec")
      lic! :install

      expect(licd_app("exec/rails")).to exist
    end
  end

  context "with --standalone option" do
    before do
      install_gemfile <<-G
        source "file://#{gem_repo1}"
        gem "rack"
      G
    end

    it "generates a standalone binstub" do
      lic! "binstubs rack --standalone"
      expect(licd_app("bin/rackup")).to exist
    end

    it "generates a binstub that does not depend on rubygems or lic" do
      lic! "binstubs rack --standalone"
      expect(File.read(licd_app("bin/rackup"))).to_not include("Gem.bin_path")
    end

    context "when specified --path option" do
      it "generates a standalone binstub at the given path" do
        lic! "binstubs rack --standalone --path foo"
        expect(licd_app("foo/rackup")).to exist
      end
    end
  end

  context "when the bin already exists" do
    it "doesn't overwrite and warns" do
      FileUtils.mkdir_p(licd_app("bin"))
      File.open(licd_app("bin/rackup"), "wb") do |file|
        file.print "OMG"
      end

      install_gemfile <<-G
        source "file://#{gem_repo1}"
        gem "rack"
      G

      lic "binstubs rack"

      expect(licd_app("bin/rackup")).to exist
      expect(File.read(licd_app("bin/rackup"))).to eq("OMG")
      expect(out).to include("Skipped rackup")
      expect(out).to include("overwrite skipped stubs, use --force")
    end

    context "when using --force" do
      it "overwrites the binstub" do
        FileUtils.mkdir_p(licd_app("bin"))
        File.open(licd_app("bin/rackup"), "wb") do |file|
          file.print "OMG"
        end

        install_gemfile <<-G
          source "file://#{gem_repo1}"
          gem "rack"
        G

        lic "binstubs rack --force"

        expect(licd_app("bin/rackup")).to exist
        expect(File.read(licd_app("bin/rackup"))).not_to eq("OMG")
      end
    end
  end

  context "when the gem has no bins" do
    it "suggests child gems if they have bins" do
      install_gemfile <<-G
        source "file://#{gem_repo1}"
        gem "rack-obama"
      G

      lic "binstubs rack-obama"
      expect(out).to include("rack-obama has no executables")
      expect(out).to include("rack has: rackup")
    end

    it "works if child gems don't have bins" do
      install_gemfile <<-G
        source "file://#{gem_repo1}"
        gem "actionpack"
      G

      lic "binstubs actionpack"
      expect(out).to include("no executables for the gem actionpack")
    end

    it "works if the gem has development dependencies" do
      install_gemfile <<-G
        source "file://#{gem_repo1}"
        gem "with_development_dependency"
      G

      lic "binstubs with_development_dependency"
      expect(out).to include("no executables for the gem with_development_dependency")
    end
  end

  context "when LIC_INSTALL is specified" do
    it "performs an automatic lic install" do
      gemfile <<-G
        source "file://#{gem_repo1}"
        gem "rack"
      G

      lic "config auto_install 1"
      lic "binstubs rack"
      expect(out).to include("Installing rack 1.0.0")
      expect(the_lic).to include_gems "rack 1.0.0"
    end

    it "does nothing when already up to date" do
      install_gemfile <<-G
        source "file://#{gem_repo1}"
        gem "rack"
      G

      lic "config auto_install 1"
      lic "binstubs rack", :env => { "LIC_INSTALL" => 1 }
      expect(out).not_to include("Installing rack 1.0.0")
    end
  end
end
